### ISSUE TITLE
V24 checklist (tentative 29.07 submission)

### ISSUE THREAD

**Issue by jpata** [vhbb/cmssw#509]
This is a meta-issue with a checklist of stuff we'd need for V24. I'd like to know in advance when we plan to submit it. I would propose end of this week (29.07).

crucial:
- [x] lepton trigger efficiencies for non-reHLT (trigger emulation): https://github.com/vhbb/cmssw/issues/508
- [x] reHLT vs no-reHLT code: https://github.com/vhbb/cmssw/issues/486
- [x] update PU: https://github.com/vhbb/cmssw/issues/505, https://github.com/vhbb/cmssw/pull/517
- [x] IsoMu22 trigger: https://github.com/vhbb/cmssw/pull/512
- [x] ICHEP b-tag scale factors: https://github.com/vhbb/cmssw/issues/519

less crucial:
- [x] update ele SF-s: https://github.com/vhbb/cmssw/issues/495
- [x] update mu SF-s: https://github.com/vhbb/cmssw/pull/516
- [x] new regression training
- [x] muon ID #481
- [ ] electron energy regression: any update??

Please add & comment!

**Comment by perrozzi** [comment]
deadline looks tight but would be perfect for VH, I think

**Comment by bianchini** [comment]
Let me also add:
- new regression training
- muon ID https://github.com/vhbb/cmssw/issues/481
- electron energy regression: any update??

**Comment by degrutto** [comment]
Hi Lorenzo,

we should also fix some ZnnHbb trigger name....

**Comment by jpata** [comment]
I think I'm ready to submit. I will merge the ticked features myself to my branch [jpata/cmssw:meanalysis-80X-V24](https://github.com/jpata/cmssw/tree/meanalysis-80x-V24).

I will submit only the ttH-relevant samples, but the code is there for also others to use Andrea's submission scripts.

**Comment by jpata** [comment]
Jobs running: [dashboard](http://dashb-cms-job.cern.ch/dashboard/templates/task-analysis/#user=Joosep+Pata&refresh=60&table=Mains&p=1&records=-1&activemenu=1&pattern=*tth_Jul31_V24_v1*&task=&from=&till=&timerange=lastMonth)

**Comment by jpata** [comment]
seems like data are not well replicated. I've made another transfer of 50TB to T2_CH_CSCS, hopefully that will make data processing smoother.

**Comment by jpata** [comment]
MC: [DAS](https://cmsweb.cern.ch/das/request?view=list&limit=50&instance=prod%2Fphys03&input=dataset+dataset%3D%2F*%2Fjpata-tth_Jul31_V24_v1*%2FUSER+status%3D*) (basically done)

Data: [DAS](https://cmsweb.cern.ch/das/request?view=list&limit=50&instance=prod%2Fphys03&input=dataset+dataset%3D%2F*%2Fjpata-tth_Aug3_V24_v2*%2FUSER+status%3D*) [dashboard](http://dashb-cms-job.cern.ch/dashboard/templates/task-analysis/#user=Joosep+Pata&refresh=60&table=Mains&p=1&records=-1&activemenu=1&pattern=*tth_Aug3_V24_v2*&task=&from=&till=&timerange=lastMonth)

I had to resubmit data with https://github.com/jpata/tthbb13/pull/88/commits/5b3cf57dc91bcc5d27e77b36fb545b6ce2ab3519 in order to have less failures and more stable running.

I've also implemented in https://github.com/jpata/tthbb13/pull/96 code that propagates the processed lumi section to DAS, so one can run `lumiCalc.py` even on partly-finished datasets, we can use that in the next runs.

**Comment by jpata** [comment]
We made another data/MC run last week, see https://github.com/jpata/tthbb13/issues/84#issuecomment-239412419

**Comment by arizzi** [comment]
we are trying to submit in the next few days, pleas review issues and provide PRs.

new base release is 8_0_19, someone should check if the updated btag SF  calibrator still makes sense (perhaps after we also switch to BTV mitigated SF in input)

**Comment by jpata** [comment]
closing this meta-issue
